### PR TITLE
Start a workflows.md document

### PR DESCRIPTION
**Pull request by alexcrichton**

### CODE REVIEW

**Comment by badboy** [comment]
Looks good to me as a first start.

**Comment by aturon** [comment]
Thanks @alexcrichton!

@badboy, feel free to merge at will :-)

**Comment by badboy** [comment]
Will do next time.

**Comment by mgattozzi** [comment]
I've started work on setting up a whole book so we can guide people from a simple hello world to more complicated things like passing data between JS and wasm. I'll try and get a PR in this weekend with the basic skeleton if this sounds good.

**Comment by alexcrichton** [comment]
Nice! 👍

**Pull request merged**
